[tasks.depot]
script = "depot build --platform linux/amd64 --tag minskylab/plexo-core:v${CARGO_MAKE_CRATE_VERSION} --push ."

[tasks.docker-build]
script = "docker build -t --platform linux/amd64 minskylab/plexo-core:v${CARGO_MAKE_CRATE_VERSION} ."
